### PR TITLE
Alpha Dev

### PR DESCRIPTION
**Pull request by nicobokhari13**
The controller files match the server's state of functionality regardless of the code quality/mess of comments. These will be cleaned up in the next feature branch. 

You will notice that in `mqtt_controller.py` that a message is published twice in `sendFalseAlarmMessage()` with two different publishing functions from the `Paho Library` (i.e. `client.publish()` and `publish.single()`. This was used to debug issues in integration, but for the future development, expect to only see `client.publish()` as the only publishing function. It is clearer, requires less code maintenance, and more secure as security parameters are already verified within the client.

### CODE REVIEW

**Comment by nicobokhari13** [comment]
Also closes Issue #6

**Review by Bcsotty — COMMENTED** [review]
Config.ini may need to be updated, seems that the links still have the old port for the API.

**Review by Bcsotty — APPROVED** [review]
LGTM!

**Comment by nicobokhari13** [comment]
The server uses the correct port number. I will remove `config.ini` and leave the sample config (which uses the correct port)

**Pull request merged**
